# Generated by Django 6.0.2 on 2026-02-07 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სადგურის სახელი')),
                ('city', models.CharField(max_length=100, verbose_name='ქალაქი')),
            ],
            options={
                'verbose_name': 'სადგური',
                'verbose_name_plural': 'სადგურები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='მატარებლის ნომერი')),
                ('train_type', models.CharField(choices=[('express', 'ექსპრესი'), ('passenger', 'სამგზავრო')], default='passenger', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=100, verbose_name='სავარძლების რაოდენობა')),
            ],
            options={
                'verbose_name': 'მატარებელი',
                'verbose_name_plural': 'მატარებლები',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, verbose_name='მარშუტის სახელი')),
                ('departure_time', models.DateTimeField(verbose_name='გასვლის დრო')),
                ('arrival_time', models.DateTimeField(verbose_name='ჩასვლის დრო')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='tickets.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tickets.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tickets.train')),
            ],
            options={
                'verbose_name': 'მარშრუტი',
                'verbose_name_plural': 'მარშრუტები',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='სავარძლის ნომერი')),
                ('seat_type', models.CharField(default='standard', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.route')),
            ],
            options={
                'verbose_name': 'დაჯავშნა',
                'verbose_name_plural': 'დაჯავშნები',
                'ordering': ['-booking_date'],
                'unique_together': {('route', 'seat_number')},
            },
        ),
    ]
