# Generated by Django 6.0.2 on 2026-02-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='საბოლოო ფასი'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_type',
            field=models.CharField(choices=[('standard', 'სტანდარტული'), ('business', 'ბიზნესი'), ('first', 'პირველი კლასი')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=100, verbose_name='მარშრუტის სახელი'),
        ),
    ]
