# Generated by Django 6.0.2 on 2026-02-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_booking_final_price_alter_booking_seat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stations/'),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trains/'),
        ),
    ]
